<?php if (!defined('ABSPATH')) exit; ?>
<footer class="site-footer" id="contact"><div class="container">
<div class="footer-grid footer-grid-compact">
 <div class="footer-col footer-about" id="about"><div class="footer-brand footer-brand-compact"><div class="electricity-logo" aria-label="لوگوی شرکت برق"><svg viewBox="0 0 64 64" role="img" aria-hidden="true"><circle cx="32" cy="32" r="31" fill="#ffd400"/><path d="M8 35c8-10 14-7 18-17 3-8 5-14 6-20 3 10 7 15 12 20 5 5 9 9 12 17" fill="none" stroke="#e51f28" stroke-width="6" stroke-linecap="round"/><path d="M29 17h8l-5 12h7L25 49l5-15h-7z" fill="#163c72"/></svg></div><div><h3><?php echo esc_html(ramser_energy_get('brand_title')); ?></h3><span><?php echo esc_html(ramser_energy_get('brand_subtitle')); ?></span></div></div><p><?php echo nl2br(esc_html(ramser_energy_get('footer_about'))); ?></p></div>
 <div class="footer-col footer-links"><h3><?php echo esc_html(ramser_energy_get('footer_services_title')); ?></h3><?php foreach(preg_split('/\|/',ramser_energy_get('footer_services')) as $x) echo '<a href="#services">'.esc_html(trim($x)).'</a>'; ?></div>
 <div class="footer-col footer-links"><h3><?php echo esc_html(ramser_energy_get('footer_access_title')); ?></h3><?php foreach(preg_split('/\|/',ramser_energy_get('footer_access')) as $x) echo '<a href="#">'.esc_html(trim($x)).'</a>'; ?></div>
 <div class="footer-col footer-contact"><h3><?php echo esc_html(ramser_energy_get('footer_contact_title')); ?></h3><?php $contact_lines=array_filter(preg_split('/\|/',ramser_energy_get('footer_contact'))); foreach($contact_lines as $index=>$line): ?><p class="contact-line contact-line-<?php echo esc_attr($index+1); ?>"><?php if($index===1): ?><a class="footer-phone" href="tel:01155256008" dir="ltr">011-55256008</a><?php else: echo esc_html(trim($line)); endif; ?></p><?php endforeach; ?><div class="footer-social" aria-label="شبکه‌های اجتماعی"><a href="#" aria-label="اینستاگرام">◎</a><a href="#" aria-label="تلگرام">◈</a><a href="#" aria-label="واتساپ">◉</a><a href="#" aria-label="اطلاعات">i</a></div></div>
</div>
<div class="footer-bottom"><div><?php echo esc_html(ramser_energy_get('copyright')); ?></div><div><?php echo esc_html(ramser_energy_get('developer')); ?></div></div>
</div></footer><?php wp_footer(); ?></body></html>
